version: 2.1

setup: true

orbs: 
  continuation: circleci/continuation@0.2.0

jobs:
  jobA:
    docker:
      - image: cimg/base:edge
    steps:
      - run: echo "jobA"

workflow:
  workflow1:
    jobs:
      - jobA
