version: 2.1

setup: true

orbs: 
  continuation: circleci/continuation@0.2.0

jobs:
  build:
    docker:
      - image: cimg/base:edge
    steps:
      - run: echo "jobA"
      - checkout
      - run: exit 1


workflows:
  firstjob:
    jobs:
      - build:
          post-steps:
            - continuation/continue:
                configuration_path: ./.circleci/config_continue.yml
                when: always
