version: 2.1

setup: true

orbs: 
  continuation: circleci/continuation@0.2.0 
  
commands:
  continue:
    parameters:
      when:
        type: enum
        enum: ["on_success", "on_fail", "always"]
        default: "on_success"
      configuration_path:
        type: string
      parameters:
        default: '{}'
        type: string
    steps:
      - run:
          when: <<parameters.when>>
          command: |
            chmod +x ./.circleci/continue.sh
            ./.circleci/continue.sh
          environment:
            CONFIG_PATH: <<parameters.configuration_path>>
            PARAMETERS: <<parameters.parameters>>
          name: Continue Pipeline

jobs:
  jobA:
    docker:
      - image: cimg/base:edge
    steps:
      - run: echo "jobA"
      - checkout
      - run: exit 1

workflows:
  firstjob:
    jobs:
      - jobA:
          post-steps:
            - continue:
                configuration_path: ./.circleci/config_continue.yml
                when: "alwaysdfsdf"
