version: 2.1

setup: true

orbs: 
  continuation: circleci/continuation@0.2.0

jobs:
  build:
    docker:
      - image: cimg/base:edge
    steps:
      - run: echo "jobA"
      - checkout


workflows:
  workflow:
    jobs:
      - build:
          post-steps:
            - continuation/continue:
                configuration_path: ./config_continue.yml
#                when: always
